Push compression metrics to StatsD/Datadog/Prometheus
zendesk/ruby-kafka pull request #868
Opened 2020-10-28 17:03 UTC by ellimist

The [Compressor](https://github.com/zendesk/ruby-kafka/blob/d3796daf8433611043f6680412b27355317896e1/lib/kafka/compressor.rb#L78-L81) class is pushing ActiveSupport notifications with metrics regarding the messages getting compressed.

However these don't get pushed to StatsD/Datadog, since there's no subscriber for them.

This PR adds the missing subscribers.

2020-10-28 18:44 UTC, livathinos approved these changes
cc @dasch

2020-10-29 10:00 UTC, dasch requested changes

2020-10-29 10:00 UTC, dasch commented on lib/kafka/datadog.rb
> +      end
I think we should add another histogram here – the compression _factor_. That's much easier to use in comparisons and evaluations of efficacy.

```ruby
histogram("compressor.compression_factor", uncompressed_bytesize / compressed_bytesize)
```

2020-10-29 10:01 UTC, dasch commented on lib/kafka/prometheus.rb
> +        @compressed_bytesize.set(compressed_bytesize)
Does Prometheus support histograms? I'd assume so.

2023-10-05 00:11 UTC, closed without merging