AWS IAM SASL auth for MSK
zendesk/ruby-kafka pull request #907
Opened 2021-07-21 18:46 UTC by jobeus

There wasn't support for authenticating with AWS's IAM, so here it is.

Based off instructions @ https://github.com/aws/aws-msk-iam-auth

Something along these lines to test/connect:

```
k = Kafka.new(
  seed_brokers: [array of seed brokers as defined by aws],
  client_id: 'client_id',
  logger: Rails.logger,
  partitioner: Kafka::Partitioner.new,
  sasl_aws_msk_iam_access_key_id: 'iam_access_key',
  sasl_aws_msk_iam_secret_key_id: 'iam_secret_key',
  sasl_aws_msk_iam_aws_region: 'us-west-2',
  ssl_ca_certs_from_system: true
)
k.topics
```

IAM auth-enabled kafka instances should be on post 9098, so seed broker array such as `['host1.aws.com:9098', 'host2.aws.com:9098']` etc.

More instructions on how to find these hostnames for your MSK setup @ https://github.com/aws/aws-msk-iam-auth

2021-07-28 11:36 UTC, dasch requested changes
Thanks for opening this PR! I've got some feedback before I can merge this:

1. It would be great to leverage standard library methods a bit more – I'm a bit worried about the amount of low level code introduced here.
2. I would love to see this tested in production before merging. Are you currently using this?
3. There needs to be an update to the README and the changelog.

2021-07-28 11:36 UTC, dasch commented on lib/kafka/sasl/awsmskiam.rb
> +          if ('A'..'Z').include?(char) || ('a'..'z').include?(char) || ('0'..'9').include?(char) || char == '_' || char == '-' || char == '~' || char == '.'
Is this function somehow specific to AWS? We can't use normal URI encoding here? At the very least we'd need a comment describing what this does, and why.

2021-07-28 11:36 UTC, dasch commented on lib/kafka/sasl/awsmskiam.rb
> +        aws_uri_encode("X-Amz-SignedHeaders") + "=" + aws_uri_encode("host")
Perhaps use <https://ruby-doc.org/stdlib-2.6.3/libdoc/uri/rdoc/URI.html#method-c-encode_www_form> here instead.

2021-11-24 19:03 UTC, garrett528 commented
@jobeus pulled this branch and keep getting `Could not connect to any of the seed brokers: (Kafka::ConnectionError)
SASL AWS_MSK_IAM authentication failed: end of file reached`. doesn't seem to make it past the `encoder.write_bytes(msg)` call. 

have you run into this? i can get this to work with multiple other clients on my machine (`librdkafka`, the standard Java client, etc.)

i don't see anything wrong with your code but was wondering if you had run into this since it's unclear why the metadata fetch is failing. 

once i can get this working, i want to extend this to add support for temp credentials / AssumeRole refreshes.

2021-11-26 18:43 UTC, garrett528 commented
figured out the issue here. when building the timestamp to be used to calculate the various parts of the signature, the code needs to call `Time.now.utc` instead of `Time.now` to ensure the timestamp is using UTC and not a local timezone. furthermore, the timestamp should be determined before calling `authentication_payload` and that single timestamp value should be passed through the call to each area of the signature process that requires the current datetime timestamp instead of calling `Time.now` each time.

2022-03-02 21:01 UTC, kirkokada commented
Hi @jobeus @dasch , I am interested in using this feature in production, is there anything I can help with to get this merged? 

Looks like to fix the unit tests all you need to do is add a few lines to `spec/sasl_authenticator_spec.rb` 

```ruby
# spec/sasl_authenticator_spec.rb:33

  let(:auth_options) {
    {
      # ...
      sasl_aws_msk_iam_access_key_id: nil,
      sasl_aws_msk_iam_secret_key_id: nil,
      sasl_aws_msk_iam_aws_region: nil
    }
  }
```

2022-03-28 19:23 UTC, jobeus commented
Continued better in #937 let's get this merged :D

2022-03-28 19:23 UTC, closed without merging